version: '3'

services:
  pqx-server:
    restart: always
    container_name: ${PQX_CONTAINER_NAME}
    image: ${PQX_IMAGE_NAME}:${PQX_IMAGE_VERSION}
    init: true

    ports:
      - "25677:8080"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/app:z # config folder
      - ${WORK_DIR_O}:${WORK_DIR_I}:z # work dir

    entrypoint: [ "sleep", "infinity" ]

networks:
  default:
    name: ${PQX_NET}
    # external: true
