version: '3'

services:
  mq:
    restart: always
    container_name: ${PQX_FACILITIES_MQ_CONTAINER_NAME}
    image: ${PQX_FACILITIES_MQ_NAME}:${PQX_FACILITIES_MQ_VERSION}
    environment:
      RABBITMQ_DEFAULT_USER: ${USER}
      RABBITMQ_DEFAULT_PASS: ${PASS}
      RABBITMQ_DEFAULT_VHOST: ${VHOST}

    ports:
      - "5677:5672"
      - "15677:15672"
    volumes:
      - ./mq/:/var/lib/rabbitmq/:z
      - /etc/localtime:/etc/localtime:ro

  pg:
    restart: always
    container_name: ${PQX_FACILITIES_PG_CONTAINER_NAME}
    image: ${PQX_FACILITIES_DB_NAME}:${PQX_FACILITIES_DB_VERSION}
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5437:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg:/var/lib/postgresql/data:z
      - /etc/localtime:/etc/localtime:ro

# networks:
#   default:
#     name: pqx-dev-net
#     external: true
