#!/usr/bin/env bash
# author:	Jacob Xie
# @date:	2023/06/24 00:26:36 Saturday
# @brief:

# determine which .env to use
if [[ -z "${DEPLOY_ENV}" ]]; then
  src="../default.env"
else
  src="../${DEPLOY_ENV}.env"
fi
echo using $src for deployment
source $src

echo "PQX_FACILITIES_MQ_CONTAINER_NAME: " $PQX_FACILITIES_MQ_CONTAINER_NAME
echo "PQX_FACILITIES_MQ_NAME: " $PQX_FACILITIES_MQ_NAME
echo "PQX_FACILITIES_MQ_VERSION: " $PQX_FACILITIES_MQ_VERSION
echo "PQX_FACILITIES_PG_CONTAINER_NAME: " $PQX_FACILITIES_PG_CONTAINER_NAME
echo "PQX_FACILITIES_DB_NAME: " $PQX_FACILITIES_DB_NAME
echo "PQX_FACILITIES_DB_VERSION: " $PQX_FACILITIES_DB_VERSION
echo "USER: " $USER
echo "PASS: " $PASS
echo "VHOST: " $VHOST
echo "DATABASE: " $DATABASE

export PQX_FACILITIES_MQ_CONTAINER_NAME=$PQX_FACILITIES_MQ_CONTAINER_NAME
export PQX_FACILITIES_MQ_NAME=$PQX_FACILITIES_MQ_NAME
export PQX_FACILITIES_MQ_VERSION=$PQX_FACILITIES_MQ_VERSION
export PQX_FACILITIES_PG_CONTAINER_NAME=$PQX_FACILITIES_PG_CONTAINER_NAME
export PQX_FACILITIES_DB_NAME=$PQX_FACILITIES_DB_NAME
export PQX_FACILITIES_DB_VERSION=$PQX_FACILITIES_DB_VERSION
export USER=$USER
export PASS=$PASS
export VHOST=$VHOST
export DATABASE=$DATABASE

docker-compose down
docker-compose up -d
